apiVersion: v1
kind: Service
metadata:
  name: identity-manager-service
spec:
  selector:
    app: identitymanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
